version: "3.7"
services:

  # the keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    command: ["start-dev"]
    ports:
      - "${KEYCLOAK_PORT}:8080"
    env_file:
      - ./config/keycloak.env
      - ./.env
    restart: unless-stopped
    depends_on:
      postgresd:
        condition: service_healthy
    networks:
      - intranet
    
  # Run a postgres instance with a persistant data volume.
  postgresd:
    image: postgres:${POSTGRES_VERSION}
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./instance/database
        target: /var/lib/postgresql/data
    env_file:
      - ./config/postgres.env
    restart: unless-stopped
    networks:
      - intranet

  ##pgbackups:
  ##  image: prodrigestivill/postgres-backup-local:latest
  ##  restart: unless-stopped
  ##  volumes:
  ##    - type: bind
  ##      source: ./instance/database/mbackups
  ##      target: /backups
  ##  depends_on:
  ##    postgresd:
  ##      condition: service_healthy
  ##  env_file:
  ##    - ./config/postgres-backup.env
  ##  networks:
  ##    - intranet

networks:
  intranet: