version: "3.7"
services:
  # the keycloak service
  keycloak:
    image: keycloak/keycloak:${KC_VERSION}
    command: ["start"]
    ports:
      - "${KEYCLOAK_PORT}:8080"
    env_file:
      - ./config/keycloak.env
      - ./.env
    #volumes: # mount local themes
    #  - type: bind
    #    source: ./instance/themes
    #    target: /opt/keycloak/providers
    restart: unless-stopped
    depends_on:
      postgresd:
        condition: service_healthy
    networks:
      - intranet

  nginx:
    image: jonasal/nginx-certbot:${NGINX_CERTBOT_VERSION}
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./config/nginx-certbot.env
    restart: unless-stopped
    volumes:
      # add :z if you have issues with permissions
      - ./instance/nginx/:/etc/letsencrypt
      - ./config/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - keycloak
    networks:
      - intranet

  # Run a postgres instance with a persistant data volume.
  postgresd:
    image: postgres:${POSTGRES_VERSION}
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - ./config/postgres.env
    restart: unless-stopped
    networks:
      - intranet

  pgbackups:
    image: prodrigestivill/postgres-backup-local:${DB_BACKUP_LOCAL_VERSION}
    restart: unless-stopped
    volumes:
      - database-backups:/backups
    depends_on:
      postgresd:
        condition: service_healthy
    env_file:
      - ./config/postgres-backup.env
    networks:
      - intranet

volumes:
  database-data:
  database-backups:

networks:
  intranet:
